-- Crea la tabla productos
create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio numeric(10,2) not null default 0,
  categoria text,
  disponible boolean default true,
  img text,
  orden integer
);

-- Índice por orden para consultas ordenadas
create index if not exists idx_productos_orden on public.productos (orden);